### ISSUE TITLE
Add more detailed documentation/demo about default behavior after login

### ISSUE THREAD

**Issue by DiegoCardoso** [vaadin/vaadin-login-flow#38]
When user submits the login, the submit button is disabled to prevent another attempt before the login is processed.

Add:
- **Documentation** describing the behavior
- **Demo** with details with what the developer should do in order to re-enable login

**Comment by tulioag** [comment]
For the documentation part, the behavior is described in AbstractLogin.
```java
/**
 * Abstract component for the {@code <vaadin-login-overlay>} and
 * {@code <vaadin-login-form>} components.
 * On {@link LoginForm.LoginEvent} component becomes disabled.
 * Disabled component stops to process login events, however
 * the {@link LoginForm.ForgotPasswordEvent} event is processed anyway.
 * To enable use the {@link com.vaadin.flow.component.HasEnabled#setEnabled(boolean)} method.
 * Setting error {@link #setError(boolean)} true makes component automatically enabled for
 * the next login attempt.
*/
```
Is this enough? Should this be replicated in the subclasses? How about a simple `@see AbstractLogin` in each subclass?
