### ISSUE TITLE
Vertical variation

### ISSUE THREAD

**Issue by appreciated** [vaadin/vaadin-login-flow#40]
I haven't really looked deep into the demo code but it looked as if there wasn't a "vertical" variation of the Login Component ([f.e. similar to this one](https://www.uplabs.com/posts/signup-page-design)). 
So are there any plan on providing one?

**Comment by alexberazouski** [comment]
Hi Current implementation of lumo theme (the theme used by default) shows the login form with the branding area on top. However, the form changes to landscape mode when the window height is smaller than `600px`.
You could check it in the [demos](https://cdn-origin.vaadin.com/vaadin-login/1.0.0-alpha9/demo/#advanced-demos)

Component has material theme as well, which has landscape mode by default. Please, check this [material demo](https://cdn-origin.vaadin.com/vaadin-login/1.0.0-alpha9/demo/index-material.html#advanced-demos).

Also keep in mind, it's possible to customize existing themes.

**Comment by appreciated** [comment]
@alexberazouski Thank you for your quick reply! I see this Component can be customized pretty heavily and easily.

I was able to get the behaviour I wanted with modifying some of the styles:
```
@media only screen and (max-height: 600px) and (min-width: 600px) and (orientation: landscape)
[part="card"] {
    flex-direction: row;
    align-items: stretch;
    max-width: calc(var(--lumo-size-m) * 16);
    width: 100%;
}
```
To the following
```
@media only screen and (min-width: 600px) {
...
}
```

Thanks for your hint 😉
